[package]
name = "wasm-test"
version = "0.0.1"
edition = "2021"
author = "Jim Eckerlein"
description = "A minimal example for compiling a Rust library to WebAssembly"
repository = "https://github.com/jim-ec/wasm-rust"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
